### ISSUE TITLE
Request to add the propagated history to the root policy status

### ISSUE THREAD

**Issue by yanmxa** [open-cluster-management-io/governance-policy-propagator#148]
For the replicated policy, I find that we have added the [event history](https://github.com/open-cluster-management-io/governance-policy-propagator/blob/830543908ac0c6f025e6f9d5aa0e6e2ab1351d41/api/v1/policy_types.go#L119) to the policy status for checking the compliance changes on the replicated policy.

Do we also consider adding the event history to the `rootPolicy` for checking the propagated updates? as follows:
```yaml
status:
...
       history: 
          eventName: *,
          lastTimestamp: *,
          message: "Policy rootpolicy-1 was propagated to  cluster cluster1"
```
